apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: tpts-inngang-flate
  namespace: tpts
  labels:
    team: tpts
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{image}}
  port: 8080
  ingresses:
    - https://tpts-inngang-flate.dev.intern.nav.no
  replicas:
    min: 1
    max: 1
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - "NAVident"
        groups:
          - id: "de1a64fd-70d7-4cb2-84e9-6c9fdf948f1b" # TPTS i Azure AD
  env:
    - name: CORS_DOMAIN
      value: "*"