name: Build, push, and deploy

on: [push]

env:
  CI: true
  TZ: Europe/Amsterdam
  docker_image: ghcr.io/navikt/tpts-inngang-flate:${{ github.sha }}

jobs:

  build:
    runs-on: ubuntu-latest
    needs: set_version
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker build --tag ${docker_image} .
          docker push ${docker_image}

  deploy:
    name: Deploy application to main
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais.yml
          VAR: image=${{ env.docker_image }}